# Generated by Django 3.2.13 on 2022-06-03 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.URLField()),
                ('contract_address', models.CharField(max_length=64)),
                ('token_address', models.CharField(max_length=64)),
                ('blockchain_network', models.IntegerField(choices=[('CELO', 0)])),
                ('auto_withdraw', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[('PENDING', 0), ('ACTIVE', 1), ('DISPUTE', 2), ('COMPLETED', 3), ('CANCELLED', 4)], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrusteeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('wallet_address', models.IntegerField()),
                ('trustee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustees', to='contract.contractmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DepositorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('wallet_address', models.IntegerField()),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositors', to='contract.contractmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
