# Generated by Django 3.2.13 on 2022-06-07 11:34

import contract.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.UUIDField(default=contract.models.generate_UUID, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('agreement', models.URLField(blank=True)),
                ('amount', models.IntegerField()),
                ('contract_address', models.CharField(blank=True, max_length=64, null=True)),
                ('token_address', models.CharField(max_length=64)),
                ('blockchain_network', models.IntegerField(choices=[(0, 'CELO')])),
                ('auto_withdraw', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACTIVE'), (2, 'DISPUTE'), (3, 'COMPLETED'), (4, 'CANCELLED')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrusteeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('wallet_address', models.CharField(max_length=64)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trustees', to='contract.contractmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'contract')},
            },
        ),
        migrations.CreateModel(
            name='DepositorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('wallet_address', models.CharField(max_length=64)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositors', to='contract.contractmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'contract')},
            },
        ),
    ]
