# Generated by Django 3.2.13 on 2022-06-05 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trusteemodel',
            old_name='trustee',
            new_name='contract',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositormodel',
            name='contract',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='depositors', to='contract.contractmodel'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='depositormodel',
            unique_together={('user', 'contract')},
        ),
        migrations.AlterUniqueTogether(
            name='trusteemodel',
            unique_together={('user', 'contract')},
        ),
        migrations.RemoveField(
            model_name='depositormodel',
            name='depositor',
        ),
    ]
