# Generated by Django 3.2.13 on 2022-06-10 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='blockchain_network',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='token_address',
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coin.tokenmodel'),
            preserve_default=False,
        ),
    ]
