# Generated by Django 3.2.13 on 2022-06-06 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20220605_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='contract_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
