# Generated by Django 3.2.13 on 2022-06-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_alter_contractmodel_contract_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='agreement',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='blockchain_network',
            field=models.IntegerField(choices=[(0, 'CELO')]),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACTIVE'), (2, 'DISPUTE'), (3, 'COMPLETED'), (4, 'CANCELLED')], default=0),
        ),
        migrations.AlterField(
            model_name='depositormodel',
            name='wallet_address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='trusteemodel',
            name='wallet_address',
            field=models.CharField(max_length=64),
        ),
    ]
