# Generated by Django 3.2.13 on 2022-06-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_auto_20220606_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
