version: "3.7"

services:
  django:
    build: .
    container_name: django
    restart: on-failure:5
    env_file:
      - ./escrow/.env
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    command: bash -c "python manage.py collectstatic --no-input && python manage.py makemigrations --no-input && python manage.py migrate --no-input && gunicorn --workers=2 --bind=0.0.0.0:8000 escrow.wsgi:application"
  celery:
    container_name: celery
    restart: on-failure:5
    env_file:
      - ./escrow/.env
    build: ./
    command: celery -A escrow worker -l  info
    volumes:
      - ./:/usr/src/app/
  celery_heartbeat:
    container_name: celery_heartbeat
    restart: on-failure:5
    env_file:
      - ./escrow/.env
    build: ./
    command: celery -A escrow beat -l  info
    depends_on:
      - celery
    volumes:
      - ./:/usr/src/app/
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/logs:/etc/nginx/logs
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/others:/etc/nginx/others
      - ./config/nginx/security:/etc/nginx/security
      - ./staticfiles:/staticfiles
    depends_on:
      - django
      - ssl
    env_file:
      - ./escrow/.env
  ssl:
    build: ./config/nginx
    container_name: ssl
    volumes:
      - ./config/nginx/security:/etc/nginx/security
    entrypoint: bash -c "/etc/nginx/security/setup.sh"
    env_file:
      - ./escrow/.env