# Generated by Django 3.2.13 on 2022-05-31 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='Igx0VZlwzW_f6eZ=BbU8#W6J5M>!!*>oQ=s)g8q=&$C((hAwUb,2RSO63^.36kU^tS', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 23, 58, 15, 480346)),
        ),
    ]
