# Generated by Django 3.2.13 on 2022-05-31 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220531_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordlessusermodel',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='tKpvbOlrr9r6WAwy%U>1=$uERw?L0C9#4)P*-MNlG3jPabE7zU=vP^69d90u5$_y', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 23, 59, 58, 154946)),
        ),
    ]
