# Generated by Django 3.2.13 on 2022-05-31 23:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220531_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='jz.&lveaYlZugmzeNKx7oF+><VOPjGUM?(yJLZRUchG^s2u-bO=97uT_EMs+Xkj=pU9cHZOgC.K2bRcUBqdDj7NGV&g8fLh#jX1?L+NZiAqN37a,ZVk', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 23, 27, 16, 107466, tzinfo=utc)),
        ),
    ]
