# Generated by Django 3.2.13 on 2022-06-01 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import user.fields
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220601_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='l&?u9CHAts$7hnmFnCO-MdNrXlWw.SgOEQ-xAMYccH=6+Wk-+E,.(O1EHgQqpoWfWWVGY7stPyfc.um5WVK1uP%DM#!n.U(PZ2dF4', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 12, 1, 44, 935216, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='passwordlessusermodel',
            name='username',
            field=user.fields.UsernameField(blank=True, max_length=16, null=True, unique=True, validators=[user.validators.validate_username]),
        ),
    ]
