# Generated by Django 3.2.13 on 2022-06-01 14:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220601_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='Jj.&g$r2-,Hm8KIW0W8.y9jjeSvD)P9Am<<<e$JY$Bu<>Wpq7ico-$eobEl^Qi)8KR>2%pLRVtW=.=IzK7fmcPtr#0cGCY*Zg<tomeUht7G.<vQ#5umA#b66F^1gb', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 14, 5, 25, 881118, tzinfo=utc)),
        ),
    ]
