# Generated by Django 3.2.13 on 2022-06-02 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20220601_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='bFXVQq,azo0$.j)7Zq8gZ!*PXRPv.!Rc8DflEM>$OovS946)?uAUS>Ce30FCZ.i<^p*_p(dtP=qG$8$71,JHLx4$=ioj22mlp.3A2hOM<M5(M', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 15, 58, 57, 940390, tzinfo=utc)),
        ),
    ]
