# Generated by Django 3.2.13 on 2022-06-02 21:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import user.fields
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20220602_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='VgyJCg0g_8dC)oqZVerGEmvHf$JqyDONCpw^*V0g%DaMUvd7Y<FB?b7aR=nk7lfY?>Vx,58^upILT&1?!%hWu6ZEG^+3F,r0AyN&F4-)36(wJ9Lo&eG83RFY1$d>', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 21, 19, 58, 4355, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='passwordlessusermodel',
            name='username',
            field=user.fields.UsernameField(blank=True, max_length=16, null=True, validators=[user.validators.validate_username]),
        ),
    ]
