# Generated by Django 3.2.13 on 2022-06-03 01:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220602_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='4!GF3ZNbH=9DwoZ=t2Kxw40-F,(X!f3HEna9xYz$o7jMoiIKa5WBPFn7>iM&*FIiQza.ak=n)M-dy)EmwYsIDHj6&U?Of', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 1, 5, 33, 701530, tzinfo=utc)),
        ),
    ]
