# Generated by Django 3.2.13 on 2022-06-03 01:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20220603_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='h88iQta).ci-Ago4pY9h2uwPEpyyt14zQ,^382>>&A4j(Bkr6l*pWb5?HfLJihA>g=cSEU,9G3$aV2ocAa3ZbXui', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 1, 5, 44, 486667, tzinfo=utc)),
        ),
    ]
