# Generated by Django 3.2.13 on 2022-06-03 01:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220603_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='RW+DrVKvaoPwT)tb3ku2Dr1lOUE4U6&x_epjN!p6L?z-_nKq_GQLftI(Xu9-#!AkKNgt6*4y!o', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 1, 37, 8, 436731, tzinfo=utc)),
        ),
    ]
