# Generated by Django 3.2.13 on 2022-06-03 01:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220603_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='#&%ttl_freB5DaCn+4lP505kC>lQDVTA7S=%+U<oELlA8k,wB(2Sy48A+iI5UMP.l_^)a.<wiSV5u)<', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 1, 37, 19, 72600, tzinfo=utc)),
        ),
    ]
