# Generated by Django 3.2.13 on 2022-06-03 01:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220603_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='kS6AQ$SHX((ZZ,oX>D$cYuKPz3tAVx$kcXCjJJUa$.x8i$OtP6Neqv!vTeKu0A&UmfE$CTZp*xDBpTYUiu111l<8zOl6w', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 1, 37, 28, 778213, tzinfo=utc)),
        ),
    ]
