# Generated by Django 3.2.13 on 2022-06-03 01:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20220603_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='(xP1egCuuLUyKvT0q$QM7,ArV_.&r*%E8sq>%J*%KE7$KrwU%xt2KweIFpMCz1R8YAC^XDx9nq+8BAVH%,>#QzjA7-83z%ZOA3lz-El<qM=K', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 1, 37, 36, 229712, tzinfo=utc)),
        ),
    ]
