# Generated by Django 3.2.13 on 2022-06-03 01:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20220603_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='1WFk>d,lgK?N7)Z0Ug(ZTZ.?OLt0gDUO$MxfAROrkn,?Yo8H*+QAK^W,d<?qmxp2hjTRKmzih*z<<i?_R#$njWrKDn#?rRMdAW%Ts*vjtu=2=E9N!', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 1, 55, 54, 846377, tzinfo=utc)),
        ),
    ]
