# Generated by Django 3.2.13 on 2022-06-03 01:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_auto_20220603_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='LS_Y7yu)iV.=u%2xO6Rvuh3yg=^=5XsEXyQ3-#NR9nh&##_v)j)G^u!<BU3hzpB>t70^v_.WpU', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 1, 56, 12, 324328, tzinfo=utc)),
        ),
    ]
