# Generated by Django 3.2.13 on 2022-06-03 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20220603_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='RN7vgL2D9oM*nVjuucj&x,htvrG=cJ,&y.+x^*gMn*a#qkFe27OU^jZf^nee_G2XYC?h!0#TsP!QK5tSTZEWXd9&IN4f12o3_oBDRl0WAdd5<4l', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 2, 11, 14, 633722, tzinfo=utc)),
        ),
    ]
