# Generated by Django 3.2.13 on 2022-06-03 02:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20220603_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='41Z>c?zNQEs2CTm%v!AtG1syFS.L5!T-T+$St!icy8l-xX^&,S4A#AE,xJ9DGmkCcOfiqUn*lAfqu4gX7', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 2, 11, 22, 819718, tzinfo=utc)),
        ),
    ]
