# Generated by Django 3.2.13 on 2022-06-03 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_auto_20220603_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='CuI+1UI<90!Ihz2b1zz%R^T.tt4Q0dQ0qTkGVkAu=L>Z2#QRUi)jhDv3eHGvK05.RBpn>mNTYkYUStddFYjL(*OP3SVL,Y)nMr0?k65Wcd3y8E&3H<jx%)1intPuFqW', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 19, 52, 49, 95013, tzinfo=utc)),
        ),
    ]
