# Generated by Django 3.2.13 on 2022-06-03 23:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20220603_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='.smMYPSM4Mbu)G7.Z4TYomn$iNpv^kwMnnd3*w#4nW!D56Nc1^,evkeVZ7B#s6OUra=5E1Gkdel4=mXvL(t2ET6pRP>f8D)wDv9pTUZ', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 23, 50, 48, 963431, tzinfo=utc)),
        ),
    ]
