# Generated by Django 3.2.13 on 2022-06-04 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20220603_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='$+.rtylCMKCUe)bHuKvfuQ0A8,lHUZU9Qbkb4hX0-VUc%*cyNZAY-i((xqC2uGFi&17_fLB$?Q6sv&d-n2a-D0TA?se%$Q)Av$LJ<)I?yU2mM&', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 17, 49, 18, 503755, tzinfo=utc)),
        ),
    ]
