# Generated by Django 3.2.13 on 2022-06-04 17:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20220604_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='kmlAfOW0^2,(.>9%xbiKjdYrAX$P6e+.k2n$fi8Dn&37x9,iaeR^VcPj#M(,UpYkjufQnaJ7', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 17, 50, 25, 98373, tzinfo=utc)),
        ),
    ]
