# Generated by Django 3.2.13 on 2022-06-04 17:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20220604_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='Hsd2$)XGfOGA_#VjZNWHBqQG4h69%N(C-RU(W%E4HZ%V#UUrvp4#wzQxqMovUGW0F9uNchqdmaQ.$P$l5!_J!s_+psPhkq&pQ+ZhKxCTKVpZjIfkDOIa74FtE&b2&-+', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 17, 50, 38, 896103, tzinfo=utc)),
        ),
    ]
