# Generated by Django 3.2.13 on 2022-06-04 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20220604_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='z>rl>ZVseRlhebQ$qs-yTg2kJ0P1m&1vaK%v4l4D%WbCp518?%K^mayN(Bqo63FjV4nCeTt&c+oTTGKXRL$aCTKY8Cq+)6L6!HCXZ1', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 17, 50, 59, 895452, tzinfo=utc)),
        ),
    ]
