# Generated by Django 3.2.13 on 2022-06-04 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_auto_20220604_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='ALYHKYdWY(AQa,!b$7qokFgJS)4vPF_celgX-5=Rwo>paTC2pKjWrcSgk5i6w<V<x8cNL9q^?^>jm2n-?v*?ws&T^T3', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 17, 51, 12, 406852, tzinfo=utc)),
        ),
    ]
