# Generated by Django 3.2.13 on 2022-06-04 17:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_auto_20220604_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default=',.%l==Z%W79)l-q.Aa<f-MtDQH01zgs5*J(omrhFyp#iV?0GhzGK^^vYGW$yy>vC1dq39ZY-z7W2jXf)T6Xt)ox?!*%hFAp-RJ6ODVF?NN*,', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 17, 56, 50, 645723, tzinfo=utc)),
        ),
    ]
