# Generated by Django 3.2.13 on 2022-06-04 17:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_auto_20220604_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='Oa^Zr%WFu4DwR=ldIaXsSa1JFMl>S8OSTJNxR11mvvwxQYzw<YVt^?l7r>*p3)?^O9PGx5F(sMdu*&V9a.I8M!IkBIfJkkuahbPq#xPShXa46NcizX,2!oTzT=N_+E', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 17, 56, 57, 847215, tzinfo=utc)),
        ),
    ]
