# Generated by Django 3.2.13 on 2022-06-04 17:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_auto_20220604_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='cLVCMJsrzFOc9o2NP<dU*u.1L(Aa^v_q-?26^vwG10qBZg-N!gVX2BnWT(S,??xk*U(n%Nck*CgY1,o%>dspNW&cnMik6Mk!NyP_nkbTlYvqnxd.^C)qBfu4E', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 17, 57, 4, 804072, tzinfo=utc)),
        ),
    ]
