# Generated by Django 3.2.13 on 2022-06-04 18:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_auto_20220604_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='<Mn53hn&.^dkCZ4Pu,+ZGE1qC3t!-sYyn39NyT-KyG!4xIOZ#IODm8X7Fim3?PVKFW=>dLE%&5vh', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 18, 17, 40, 622863, tzinfo=utc)),
        ),
    ]
