# Generated by Django 3.2.13 on 2022-06-04 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_auto_20220604_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='<bSX+ZDstC%W_ohpa-w>Tv6#b<kE>2RBsU,4fp=rNh,?G=R4mc>ZkLg?vY4LWc_>B1nsS6W2o!C=*=3h?*SjG8uIp=nZrtQHu6UAY7BA8s!.vF?H(yXmbe', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 18, 24, 23, 846851, tzinfo=utc)),
        ),
    ]
