# Generated by Django 3.2.13 on 2022-06-04 18:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_auto_20220604_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='(lcb#nBd%6Z<ca,eh^&ZdX82x+#5b+QHqp9=xofCpfwP7!(?>qBnRRiWJuZmM>=cW(UkOWPal85h118E2C', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 18, 34, 46, 804891, tzinfo=utc)),
        ),
    ]
