# Generated by Django 3.2.13 on 2022-06-04 18:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_auto_20220604_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='(5qKj4e_UO>aWH=3OldfckeA(xvbfK(#ZzZ)9g0B%7uQr^XS9,JkR2O3Sk$2AziLsII,0hyRoBK(4(qfLWBH%g.KutFiTxt%BRGw&isaOy.d,', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 18, 42, 6, 135509, tzinfo=utc)),
        ),
    ]
