# Generated by Django 3.2.13 on 2022-06-04 18:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_auto_20220604_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='9bLQ>?s99)ow3VDe7H%o.B7t0*>2OyKUL4^-=d&fEm&Yd+#hh+FQA!q_PNC=yMPP0dipmLo,+8pyuiMC99tG&$AfzT_7VTl4', max_length=128),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 18, 47, 4, 852268, tzinfo=utc)),
        ),
    ]
