# Generated by Django 3.2.13 on 2022-06-04 18:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0040_auto_20220604_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='ZxITY&_0<*A0Q1Wi>sDCI)Ek_K=7!%fRNRd?VC>cNxQHQ(Y=j_P+?B#BXPEXp%RZIiSZ,oDh6Iw#pCaKZNT', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 18, 58, 46, 68460, tzinfo=utc)),
        ),
    ]
