# Generated by Django 3.2.13 on 2022-06-04 19:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0041_auto_20220604_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='ck+qj3JM(aHll4<Y=G#?uNdWpJB4jX6s+^Z8^CU+9!-j?MV(P-1!4PeYjL%6%lz-jOvtYxIWwEcpS75_', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 19, 7, 32, 562756, tzinfo=utc)),
        ),
    ]
