# Generated by Django 3.2.13 on 2022-06-04 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0043_auto_20220604_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='^IUo-hSvk+Qp%dq=+O5QEoO=.ZDGP!$?cXdtFS#643i04KQvu!Mx3qi)xu(>x*Zh9vGa<eW(6QKbGcSdpNpr', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 20, 8, 49, 776052, tzinfo=utc)),
        ),
    ]
