# Generated by Django 3.2.13 on 2022-06-04 20:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0044_auto_20220604_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='3?qNk2_hbHmhz5%h0vweIfbWf=FTq(1dC&GnKOloDR%?tIakuR(qp^?sptnZX#4nu3G*#^E(4a1Ngwf^ziI>LTilPmETMOGeLXX$c4', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 20, 12, 48, 721983, tzinfo=utc)),
        ),
    ]
