# Generated by Django 3.2.13 on 2022-06-04 20:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0046_auto_20220604_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='pjIh29*D?FxXrbj8622I6LeGRay1*9%P5Qy!vzI#mS43e5r3M3*9vUA9anm(uj-0jv!XnA2S^$=s', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 20, 27, 9, 946221, tzinfo=utc)),
        ),
    ]
