# Generated by Django 3.2.13 on 2022-06-04 20:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0047_auto_20220604_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='CYI%Y%fupWvsb%iZgiW8iPeK59TLDCH+OKx.YDqO9C,HpgWNi)DW!ADmxQtlWC>p5At3^ncnpAw<fQ2._-Po8iD6Id_q0-fj$w47NY', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 4, 20, 43, 1, 159946, tzinfo=utc)),
        ),
    ]
