# Generated by Django 3.2.13 on 2022-06-05 21:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0048_auto_20220604_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='code',
            field=models.CharField(default='q&dBo#9%LQ41r-tau_3wnWT>dj<rC3s)H9-jgyH+.8dKS33kVE!dv)7TA)?MJvpX=EY#)2%odVsyD0mySqkzQAlKHs*9co6CG?2D^+*dp+q6', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='expiry_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 21, 37, 24, 306274, tzinfo=utc)),
        ),
    ]
