# Generated by Django 3.2.13 on 2022-06-10 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainNetworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('rpc', models.URLField()),
                ('chain', models.IntegerField()),
                ('explorer', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('contract', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=8)),
                ('decimal', models.IntegerField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coin.blockchainnetworkmodel')),
            ],
        ),
    ]
