# Generated by Django 3.2.13 on 2022-06-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchainnetworkmodel',
            name='icon',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tokenmodel',
            name='icon',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
